apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
spec:
  destination:
    namespace: eks-sample-app
    server: "https://kubernetes.default.svc"
  project: target
  source:
    path: charts/github-actions-runners/chart
    repoURL: "https://github.com/22Pradeep/k8s-training.git"
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
