apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  labels:
    dnp: test
    dnp1: test2
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: eks-sample-app
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: Charts/mychart
    repoURL: "https://github.com/22Pradeep/k8s-training.git"
    targetRevision: main
    helm:
      values: |
        topologySpreadConstraints: {{- toYaml .Values.topologySpreadConstraints | nindent 8 }}
        app-namespace: dnptest
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
